# Generated by Django 3.2.12 on 2022-02-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='%Y%m%d/')),
                ('predict', models.CharField(default='无预测结果', max_length=12)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cat',
            },
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户id')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='用户名称')),
                ('password', models.CharField(max_length=30, verbose_name='用户密码')),
                ('superuser', models.IntegerField(choices=[(0, '普通用户'), (1, '管理员')], default=0, verbose_name='身份')),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
