# Generated by Django 3.2.12 on 2022-02-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cat_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='predict',
            field=models.CharField(default='无预测结果', max_length=60),
        ),
    ]
